In [ ]:
# Author: Brandon D. Jordan
# Date started: 05//2023
# Obj: analyses of blastn query searching for ***** (a case searching for matches to the soybean-specific centromeric repeats CentGm-1/2 is shown here) )

In [3]:
# import modules
import pandas as pd 
import os
# import itertools

### Tools for changing dir, listing files

### Load file and format

In [26]:
# load blast results in tabulated format; skip header rows.
gen = pd.read_csv('/Users/bjordan/Documents/work/soy_comp/snps_proj_01/blastn.all.nt/out.blastn.centgm1-2.Wm82_NJAU.gnm1.N4GV.tsv',
                  header=None,names=['qseqid', 'sseqid', 'pident', 'length', 'mismatch', 'gapopen', 'qstart',
                  'qend', 'sstart', 'send', 'evalue', 'bitscore'],
                  sep='\t', comment='#')#,on_bad_lines='warn',low_memory=False) # on_bad_lines='warn', dtypes=[]
                # I am still getting 13 cols! from here I cant tell where its values come from, so I will delete
                # the entire column and proceed...I ended up realizing the tabulated outfrmt "8" blastn results 
                # had two TABs repeated at 69 positions in the file. After trying multiple ways to fix the issue
                # via the commandline, I opted to find and replace in TextEdit for a quick fix. Comment lines can
                # can be ignored as in the above ex. or by using awk. To QC my 13 col issue, I added a col 'other'
                # here. Once the isse was resolved, the 13th col read nan for its unique values.

In [27]:
# sort df by 'sseqid' starts
gen = gen.sort_values(by = ['sseqid','sstart'])

### subset df to compare chrs within and among assemblies

In [7]:
# Create list of values [Gm01,Gm02,Gm03...Gm20] or [Chr01...Chr20]

# create a list of integers 1-9
chr_list1 = [*range(1,10)] # note what occurs when run without the '*'
chr_list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
# create a list of chr designations (i.e. Gm01,Gm02,etc)
chr_list1 = [*range(1,10)] # create a list of integers 1-9
chr_list = [str(x) for x in chr_list1] # make the list elements strings 
chr_list = ["0" + s for s in chr_list] # append a '0' to the beginning of each element
chr_list2 = [*range(10,21)] # create a list of integers 10-20
chr_list = chr_list+chr_list2 # concatenate the two lists
chr_list = [str(x) for x in chr_list] # make the list elements strings
chr_list = ["Gm" + s for s in chr_list] # append 'Gm' to each element of list # append 'Chr' for other cases...
chr_list # print list

['Gm01',
 'Gm02',
 'Gm03',
 'Gm04',
 'Gm05',
 'Gm06',
 'Gm07',
 'Gm08',
 'Gm09',
 'Gm10',
 'Gm11',
 'Gm12',
 'Gm13',
 'Gm14',
 'Gm15',
 'Gm16',
 'Gm17',
 'Gm18',
 'Gm19',
 'Gm20']

## subset df to filter by matches %-identity (>=90%)  query

In [29]:
# subset only centromeric elements found on chr's not scaffolds. Soybean chrs are denoted as Chr or Gm. Scaffolds contain an 's' in the filename.
gen_sub = gen[gen.sseqid.str.contains("Gm", regex= True, na=False)].sort_values(by = ['sseqid','sstart'])
# gen_sub.tail()
gen_sub

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore
313402,CentGm-1,glyma.Wm82_NJAU.gnm1.Gm01,84.444,45,7,0,45,89,7188645,7188601,0.000058,50.9
313403,CentGm-1,glyma.Wm82_NJAU.gnm1.Gm01,84.444,45,7,0,45,89,7188861,7188905,0.000058,50.9
315560,CentGm-1,glyma.Wm82_NJAU.gnm1.Gm01,91.667,24,2,0,5,28,7698623,7698600,1.300000,35.6
315704,CentGm-1,glyma.Wm82_NJAU.gnm1.Gm01,91.304,23,2,0,5,27,9432451,9432473,4.500000,33.7
315705,CentGm-1,glyma.Wm82_NJAU.gnm1.Gm01,91.304,23,2,0,5,27,9843994,9844016,4.500000,33.7
...,...,...,...,...,...,...,...,...,...,...,...,...
87180,CentGm-1,glyma.Wm82_NJAU.gnm1.Gm20,74.627,67,15,1,23,89,36074472,36074408,0.009000,42.8
664384,CentGm-2,glyma.Wm82_NJAU.gnm1.Gm20,86.207,29,4,0,42,70,36074541,36074513,1.300000,35.6
87190,CentGm-1,glyma.Wm82_NJAU.gnm1.Gm20,87.097,31,4,0,42,72,36074542,36074512,0.110000,39.2
87219,CentGm-1,glyma.Wm82_NJAU.gnm1.Gm20,95.238,21,1,0,7,27,36536242,36536222,4.500000,34.6
87258,CentGm-1,glyma.Wm82_NJAU.gnm1.Gm20,91.304,23,2,0,5,27,36995282,36995260,4.500000,33.7

In [10]:
sub1 = gen_sub[(gen_sub.pident>=90)& (gen_sub.length>85)]
             # & (gen_sub.length>100) &(gen_sub.evalue<=0.05)]

#sub1.shape
sub1

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore
2724,CentGm-1,glyma.Wm82.gnm1.Gm02,90.110,91,9,0,2,92,22064606,22064516,3.110000e-27,124.0
2051,CentGm-1,glyma.Wm82.gnm1.Gm02,91.209,91,8,0,2,92,22067975,22067885,7.300000e-29,129.0
1751,CentGm-1,glyma.Wm82.gnm1.Gm02,92.222,90,7,0,3,92,22068980,22068891,2.090000e-29,132.0
2938,CentGm-1,glyma.Wm82.gnm1.Gm02,90.909,88,8,0,3,90,22070153,22070066,3.110000e-27,123.0
2327,CentGm-1,glyma.Wm82.gnm1.Gm02,92.045,88,7,0,4,91,22070518,22070431,2.550000e-28,128.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8340,CentGm-1,glyma.Wm82.gnm1.Gm20,92.391,92,7,0,1,92,7271875,7271784,1.720000e-30,135.0
8055,CentGm-1,glyma.Wm82.gnm1.Gm20,94.444,90,5,0,3,92,7272057,7271968,4.040000e-32,141.0
7933,CentGm-1,glyma.Wm82.gnm1.Gm20,95.604,91,4,0,2,92,7272150,7272060,2.720000e-34,147.0
8451,CentGm-1,glyma.Wm82.gnm1.Gm20,92.222,90,7,0,1,90,7272243,7272154,2.090000e-29,132.0
8547,CentGm-1,glyma.Wm82.gnm1.Gm20,93.103,87,6,0,6,92,7272514,7272428,2.090000e-29,131.0

In [ ]:
sub1.qseqid.value_counts()

In [21]:
sub2 = gen_sub[(gen_sub.pident>=90)& (gen_sub.length>75)&
               (gen_sub.sseqid.str.contains("Gm02", regex= True, na=False))&
               (gen_sub.qseqid.str.contains("CentGm-1",regex= True,na=False))]

#sub1.shape
sub2

Empty DataFrame
Columns: [qseqid, sseqid, pident, length, mismatch, gapopen, qstart, qend, sstart, send, evalue, bitscore]
Index: []

In [22]:
sub3 = gen_sub[(gen_sub.pident>=90)& (gen_sub.length>75)&
               (gen_sub.sseqid.str.contains("Gm02", regex= True, na=False))&
               (gen_sub.qseqid.str.contains("CentGm-2",regex= True,na=False))]

#sub1.shape
sub3

Empty DataFrame
Columns: [qseqid, sseqid, pident, length, mismatch, gapopen, qstart, qend, sstart, send, evalue, bitscore]
Index: []

pipe to awk '{print $2, int($9/1000000)}' | uniq -c

to get histogram

## check for overlapping elements of >=90 pident to query sequences

# Count CentGm-1 -2 / chr

In [30]:
# use regex on the subject column to subset by chr and count the number of CentGm-1 elements found
for chr in chr_list:
    print(gen_sub[(gen_sub.pident>=90)& (gen_sub.length>75)&
               (gen_sub.sseqid.str.contains(chr, regex= True, na=False))&
               (gen_sub.qseqid.str.contains("CentGm-1",regex= True,na=False))].shape[0])

18
30243
92
750
10183
0
7277
9635
13259
0
2
5248
126
17021
7869
12002
36
1709
16744
17466

In [31]:
# use regex on the subject column to subset by chr and count the number of CentGm-2 elements found
for chr in chr_list:
    print(gen_sub[(gen_sub.pident>=90)& (gen_sub.length>75)&
               (gen_sub.sseqid.str.contains(chr, regex= True, na=False))&
               (gen_sub.qseqid.str.contains("CentGm-2",regex= True,na=False))].shape[0])

487
95
943
50
0
17117
1011
0
9
5320
1148
0
0
34
0
0
176
0
49
0

# Count [other]/ chr

In [ ]:
# use regex on the subject column to subset by chr and count the number of elements found
for chr in chr_list:
    #print(chr,"\t",sub1[(sub1.sseqid.str.contains(chr, regex= True, na=False))&
    #          (sub1.qseqid.str.contains("CentGm-2", regex= True, na=False))].shape[0])
     print(sub1[(sub1.sseqid.str.contains(chr, regex= True, na=False))&
              (sub1.qseqid.str.contains("AB536703.1", regex= True, na=False))].shape[0])

# Misc.

In [9]:
# define a function to find overlapping entries
def findOverlaps(sub):
    keep = (sub
        .sort_values(by=['sstart', 'send'])
        .assign(max_End=lambda d: d['send'].cummax(),
                group=lambda d: d['sstart'].ge(d['max_End'].shift()).cumsum()))
    return keep

In [19]:
# loop through chrs finding groups of overlapping elements
keep = pd.DataFrame()
for chr in chr_list:
    chr_sub = sub2[sub2.sseqid.str.contains(chr, regex= True, na=False)]
    if chr=="Chr01": #note to change back to 'Gm' as needed
        print('hello')
        keep = findOverlaps(chr_sub)
    else:
        ball = findOverlaps(chr_sub)
        keep = pd.concat([keep, ball])

keep

hello

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore,max_End,group
24025,glycy.l75.rpt.2081,glysy.G1300.gnm1.Chr20,77.333,75,16,1,1,75,16046265,16046338,9.400000e-07,56.3,16046338,0
1000688,glyd3.l76.rpt.1601,glysy.G1300.gnm1.Chr20,80.263,76,14,1,1,76,16046338,16046264,5.310000e-10,67.1,16046338,1
1027716,glyd3.l76.rpt.1441,glysy.G1300.gnm1.Chr20,77.632,76,16,1,1,76,16046338,16046264,2.750000e-07,58.1,16046338,2
69969,glycy.l75.rpt.97,glysy.G1300.gnm1.Chr20,76.000,75,17,1,1,75,16046338,16046265,1.150000e-05,51.8,16046338,3
249924,glyd3.l75.rpt.1857,glysy.G1300.gnm1.Chr20,73.333,75,19,1,1,75,16046338,16046265,6.000000e-03,42.8,16046338,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1543010,glysy.l120.rpt.481,glysy.G1300.gnm1.Chr20,100.000,120,0,0,1,120,30875481,30875362,2.520000e-55,217.0,30875511,5251
1557733,glysy.l94.rpt.172,glysy.G1300.gnm1.Chr20,80.952,84,16,0,11,94,30875481,30875398,3.320000e-14,80.6,30875511,5251
1575289,glysy.l94.rpt.65,glysy.G1300.gnm1.Chr20,73.077,104,15,7,1,93,30875511,30875410,8.000000e-03,42.8,30875511,5252
1309552,glyfa.l111.rpt.737,glysy.G1300.gnm1.Chr20,98.507,67,1,0,3,69,30968300,30968366,5.790000e-25,117.0,30968366,5253
1541468,glyfa.l81.rpt.65,glysy.G1300.gnm1.Chr20,91.139,79,7,0,3,81,30972417,30972339,1.570000e-23,112.0,30972339,5254

In [20]:
# get groups with more than one member. Note, this does not work with full 'keep' df bc it's groups were built
# separately by chr
for chr in chr_list:
    test2 = keep[keep.sseqid.str.contains(chr, regex= True, na=False)]
    test2 = test2[test2.duplicated(subset=['group'],keep=False)==True] # parameter "keep=False" for df.duplicated() returns
                                                                # all duplicates as True. This is not the default.
    if(test2.empty!=True):
        print(chr+'contains overlapping elements')
#test2

Chr20contains overlapping elements

In [21]:
test2 = keep[keep.sseqid.str.contains('Chr20', regex= True, na=False)]
#test2 = test2[test2.duplicated(subset=['group'],keep=False)==True] # parameter "keep=False" for df.duplicated() returns
                                                                # all duplicates as True. This is not the default.
test2

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore,max_End,group
24025,glycy.l75.rpt.2081,glysy.G1300.gnm1.Chr20,77.333,75,16,1,1,75,16046265,16046338,9.400000e-07,56.3,16046338,0
1000688,glyd3.l76.rpt.1601,glysy.G1300.gnm1.Chr20,80.263,76,14,1,1,76,16046338,16046264,5.310000e-10,67.1,16046338,1
1027716,glyd3.l76.rpt.1441,glysy.G1300.gnm1.Chr20,77.632,76,16,1,1,76,16046338,16046264,2.750000e-07,58.1,16046338,2
69969,glycy.l75.rpt.97,glysy.G1300.gnm1.Chr20,76.000,75,17,1,1,75,16046338,16046265,1.150000e-05,51.8,16046338,3
249924,glyd3.l75.rpt.1857,glysy.G1300.gnm1.Chr20,73.333,75,19,1,1,75,16046338,16046265,6.000000e-03,42.8,16046338,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1543010,glysy.l120.rpt.481,glysy.G1300.gnm1.Chr20,100.000,120,0,0,1,120,30875481,30875362,2.520000e-55,217.0,30875511,5251
1557733,glysy.l94.rpt.172,glysy.G1300.gnm1.Chr20,80.952,84,16,0,11,94,30875481,30875398,3.320000e-14,80.6,30875511,5251
1575289,glysy.l94.rpt.65,glysy.G1300.gnm1.Chr20,73.077,104,15,7,1,93,30875511,30875410,8.000000e-03,42.8,30875511,5252
1309552,glyfa.l111.rpt.737,glysy.G1300.gnm1.Chr20,98.507,67,1,0,3,69,30968300,30968366,5.790000e-25,117.0,30968366,5253
1541468,glyfa.l81.rpt.65,glysy.G1300.gnm1.Chr20,91.139,79,7,0,3,81,30972417,30972339,1.570000e-23,112.0,30972339,5254

In [22]:
test2.group.value_counts()

2788    26
3325    26
5023    25
3786    24
4987    23
        ..
2084     1
2085     1
2086     1
2087     1
5254     1
Name: group, Length: 5255, dtype: int64

In [17]:
test3 = test2[(test2.group==3)] # parameter "keep=False" for df.duplicated() returns
                                                                # all duplicates as True. This is not the default.
test3

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore,max_End,group
446089,glyfa.l75.rpt.449,glysy.G1300.gnm1.Chr01,86.364,66,9,0,1,66,19039454,19039389,8.240000e-14,79.7,19039454,3

### analyze hits for trends

In [ ]:
gen.length.unique() # get number of unique values in 'length' col
gen.length.nunique() # ...using Series.nunique()
gen.length.unique().size # ...using Series.unique()
test = gen.length.value_counts() # get frequency of each unique value


# #Ctrl + "/" to block comment/uncomment
# # By using drop_duplicates()
# count = df.Courses.drop_duplicates().size
# #Count unique on multiple columns
# count = df[['Courses','Fee']].drop_duplicates().shape[0]
# print(count)
# #Count unique on multiple columns
# count = df[['Courses','Fee']].nunique()
# #count unique values in each row
# df.nunique(axis=1)

In [ ]:
# analyze lengths of hits for trends
#type(test)
test.sort_index().plot(kind='bar') # get histogram of unique values from 'length' sorted by index (i.e length values)
test
test[test>1000] # get unique values from 'length' with freq above 1000.

In [ ]:
test2 = gen.pident.value_counts() # get frequency of each unique value
test2.sort_index().plot(kind='bar') # get histogram of unique values from 'length' sorted by index (i.e length values)
test2

### Q.C.

In [ ]:
test2 = keep[keep.sseqid.str.contains("Gm", regex= True, na=False)]
test2.group.unique().size # the number of unique values in 'group' (i.e. # of groups with more than one member)
# test2.shape[0]
# test2
# conclusion: there are many overlapping elements

In [ ]:
test2[test2.group==17]
# Chr.1 group.8 is first group w/ > 1 element. 
# Here centGm-1 and CentGm-2 overlap w/ respective lengths of 46 and 30 bp, pident of 78.261 and 90.
# CentGm-2 lies within CentGm-1, so possibly internal repeats are being matched. I will try only keeping matches of 91-92 bp
# Group 9 is another interesting case for chr.1 where matches of 94-90 were found with ~75 pident. There are
# more mismatches for -Gm-2.
# More ex's: groups 13,14,15,etc. It seems that -Gm-1 and -Gm-2 are being partially matched inside of each other.
# I will try taking the match which is about the # of bps of interest.

In [ ]:
# #clear variables
#%reset

In [ ]:
# keep = (gen_sub  # !!!note this must be done by chr to be correct in later steps! otherwise centro. units from
#         # other chrs will be grouped as overlapping.
#    .sort_values(by=['sstart', 'send'])
#    .assign(max_End=lambda d: d['send'].cummax(),
#            group=lambda d: d['sstart'].ge(d['max_End'].shift()).cumsum())
#    #.groupby('group', sort=False)['Tiebreak'].idxmax()
# )

#out = gen_sub[gen_sub.index.isin(keep)]

In [ ]:
# create boxplot

# Import libraries
# import matplotlib.pyplot as plt
# import numpy as np
 
 
# # Creating dataset
# np.random.seed(10)
 
# data_1 = np.random.normal(100, 10, 200)
# data_2 = np.random.normal(90, 20, 200)
# data_3 = np.random.normal(80, 30, 200)
# data_4 = np.random.normal(70, 40, 200)
# data = [data_1, data_2, data_3, data_4]
 
# fig = plt.figure(figsize =(10, 7))
 
# Creating axes instance
# ax = fig.add_axes([0, 0, 1, 1])
 
# Creating plot
# bp = ax.boxplot(test)
 
# show plot
# plt.show()

In [ ]:
# code for ANOVA - not particularly useful here
# from scipy.stats import f_oneway

# result = f_oneway(test.index,test)
# dir(result)
# # Print rownames (i.e. index)
# for row in test.index:
#     print(row)
# # These two methods work differently...the previous was better for this work. The one here
# # printed a list of integers from 0 up. That is not how the index was shown in previous steps.
# for index, val in enumerate(test):
#     print(index,val)

In [ ]:
# show history: must verify it works...
import readline; print('\n'.join([str(readline.get_history_item(i + 1)) for i in range(readline.get_current_history_length())]))

In [3]:
# get wkdir and save
top = os.getcwd()

# change directory
os.chdir('/Users/bjordan/Documents/work/soy_comp/snps_proj_01/blastn.all.nt') 

# Get working directory files and sort
dir_list = sorted(os.listdir(os.getcwd()))

# filter out directories (or unneccesary files) from tasklist
subs = ''#'out.' # initializing substring

# using list comprehension to get string with substring
dir_list = [i for i in dir_list if subs in i]

# print list
print("Files in queue:","\n\n",dir_list)

# change directory
# os.chdir('{}/{}'.format(top,gen))

Files in queue:

 ['.DS_Store', '.ipynb_checkpoints', '10.26.2023', '10.30.2023', 'README.dir.txt', 'centgm4', 'glycy.out.blastn.txt', 'glyd3.out.blastn.txt', 'glydo.out.blastn.txt', 'glyfa.out.blastn.txt', 'glyst.out.blastn.txt', 'glysy.out.blastn.txt', 'out.blastn.Fis.ws-25_noSoftMask.txt', 'out.blastn.Fiskeby.txt', 'out.blastn.Lee.txt', 'out.blastn.Lee.ws-25_noSoftMask.txt', 'out.blastn.Lee.ws-30_noSoftM.textClipping', 'out.blastn.Lee.ws-30_noSoftMask.txt', 'out.blastn.Wm82.ISU01.NEW.2.ws-45.txt', 'out.blastn.Wm82.ISU01.NEW.4.ws-40.txt', 'out.blastn.Wm82.ISU01.NEW.txt', 'out.blastn.Wm82.ISU01.txt', 'out.blastn.Wm82.ISU01.ws-25_noSoftMask.txt', 'out.blastn.Wm82.IUS01.NEW.3.txt', 'out.blastn.Wm82.gnm2.txt', 'out.blastn.Wm82.gnm2.ws-25_noSoftMask.txt', 'out.blastn.Wm82.gnm2.ws-30_noSoftMask.txt', 'out.blastn.Wm82.gnm2.ws-35_noSoftMask.txt', 'out.blastn.Wm82.gnm2.ws-40_noSoftMask.txt', 'out.blastn.Wm82.gnm4.txt', 'out.blastn.Wm82.gnm4.ws-25_noSoftMask.txt', 'out.blastn.Wm82.gnm5.1.txt', 'out.blastn.Wm82.gnm6.1.txt', 'out.blastn.Zh13 copy.txt', 'out.blastn.Zh13.txt', 'out.blastn.Zh13.ws-25_noSoftMask.txt', 'out.blastn.glycy.ws-25_noSoftMask.txt', 'out.blastn.glyd3.ws-25_noSoftMask.txt', 'out.blastn.glydo.ws-25_noSoftMask.txt', 'out.blastn.glyfa.ws-25_noSoftMask.txt', 'out.blastn.glyst.ws-25_noSoftMask.txt', 'out.blastn.glysy.ws-25_noSoftMask.txt', 'phytoph_Chr.3', 'plots', 'results']

In [ ]:
mylist=[*range(0,5)]
#print(list(itertools.chain(*mylist))) # unpack a list inside of another list
#mylist = [j for i in mylist for j in i] # do the same using list comprehension, no import
#lambda x: x in [mylist] # should be able to use in skiprows, but didnt work properly when 
# added another number to list as [*range(0,5), 185622].
mylist

In [ ]:
del gen